group_ressource_nom = "glpi"
group_ressource_location = "West Europe"
reseaux_virtual_nom = "Malo connect"
sousreseaux_nom = "malo22"
interface_reseaux_nom = "maloint"
machine_virtuelle_name = "glpiM"
disque_management_name = "glpidata"
